# Generated by Django 4.0.5 on 2022-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='text_area',
            field=models.TextField(max_length=100),
        ),
    ]
